name: TEST - PR Validation - Main Starter

on:
  workflow_dispatch:
    inputs:
      infra_commons_tag:
        description: 'Tag of the infra-commons repository to use'
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  print_inputs:
    runs-on: ubuntu-22.04

    steps:
      - name: Print Inputs
        id: print_inputs
        run: |

          echo "- ref: \`${{ github.ref }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- infra_commons_tag: \`${{ inputs.infra_commons_tag }}\`" >> $GITHUB_STEP_SUMMARY


  extract-ref:
    runs-on: ubuntu-22.04
    outputs:
      infra_commons_tag: ${{ steps.extract_tag.outputs.infra_commons_tag }}
    steps:
      - name: Print GitHub workflow ref
        run: |
          echo "github.workflow_ref = $GITHUB_WORKFLOW_REF"
          echo "github.head_ref     = $GITHUB_HEAD_REF"
          echo "github.ref          = $GITHUB_REF"
          echo "github.sha          = $GITHUB_SHA"
          echo "github.event_path   = $GITHUB_EVENT_PATH"
          echo "github.base_ref     = $GITHUB_BASE_REF"
      
      - name: Extract and print ref/tag from current workflow
        id: extract_tag
        run: |
          echo "GITHUB_WORKFLOW_REF=${GITHUB_WORKFLOW_REF}"
          REF=$(echo "$GITHUB_WORKFLOW_REF" | cut -d'@' -f2)
          if [[ "$REF" == refs/tags/* ]]; then
            TAG="${REF#refs/tags/}"
          elif [[ "$REF" == refs/heads/* ]]; then
            TAG="${REF#refs/heads/}"
          else
            TAG="main"
          fi
          echo "Extracted tag: $TAG"
          echo "infra_commons_tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Extracted ref: $REF"

  validation:
    name: "Validation – ${{ matrix.environment }}"
    needs: extract-ref
    uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/common-pr-deployment-values-validation.yaml@main
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, vapt]
    with:
      environment: ${{ matrix.environment }}
      infra_commons_tag: ${{ needs.extract-ref.outputs.infra_commons_tag }}
