name: Caller Workflow
run-name: "${{ github.ref_name }} / ${{ inputs.environment }} - Caller"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: environment
      infra_commons_tag:
        description: 'Tag of the infra-commons repository to use'
        required: false
        type: string
        default: ''
      kind:
        description: 'Kind of resource to deploy (microservice or cronjob)'
        required: true
        type: choice
        default: 'microservice'
        options:
          - microservice
          - cronjob
      target:
        description: 'Name of the target resource to deploy'
        required: true
        type: string
     

permissions:
  id-token: write
  contents: read

jobs:
  print_inputs:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Print Inputs
        id: print_inputs
        run: |
          echo "- environment: \`${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- ref: \`${{ github.ref }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- infra_commons_tag: \`${{ inputs.infra_commons_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- kind: \`${{ inputs.kind }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- target: \`${{ inputs.target }}\`" >> $GITHUB_STEP_SUMMARY
  
  extract-infra-commons-tag:
    runs-on: ubuntu-22.04
    outputs:
      resolved_infra_commons_tag: ${{ steps.extract-infra-commons-tag.outputs.infra_commons_tag }}
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Extract tag from reusable workflow
        id: resolve
        run: |
          echo "Extracting tag from reusable workflow (wf version ${{github.ref}})"

          fullref=$(yq e '.jobs.validation.uses' .github/workflows/pr-validation-main.yaml)

          tag=${fullref#*@}

          echo "fullref=$fullref"
          echo "tag=$tag"

          if [[ -n "${{ inputs.infra_commons_tag }}" ]]; then
            # uses the tag provided by the user
            final_tag="${{ inputs.infra_commons_tag }}"
          else
            # uses the tag from the reusable workflow
            final_tag="$tag"
          fi
          echo "infra_commons_tag=$final_tag" >> $GITHUB_OUTPUT
      
      - name: Show extracted tag
        run: echo "infra_commons_tag = ${{ steps.resolve.outputs.infra_commons_tag }}"


  validation:
    needs: [print_inputs, extract-infra-commons-tag]
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, vapt]
    secrets: inherit
    uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/common-pr-deployment-values-validation.yaml@main
    with:
      infra_commons_tag: ${{ needs.extract-infra-commons-tag.outputs.resolved_infra_commons_tag }}
      environment: ${{ inputs.environment }}
