name: PR Validation - Main Starter - reusable workflow 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    name: "Validation – ${{ matrix.environment }}"
    #needs: setup
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, vapt]
    uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/common-pr-deployment-values-validation.yaml@main
    with:
      environment: ${{ matrix.environment }}