# name: PR Validation - Main Starter - reusable action

# on:
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   validation:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         environment: [dev, qa, vapt]
#     steps:
#       - name: Executing validation
#         uses: roberto-mondello-dgt/cache-helm-test/actions/deployment-values-validation@main
#         with:
#           environment: ${{ matrix.environment }}
#           infra_commons_tag: main 

name: PR Validation - Main Starter - reusable workflow 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, vapt]
    steps:
      - name: Calling reusable workflow
        run: |
          echo "Workflow started for environment: ${{ matrix.environment }}"
        
      - name: Executing validation
        uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/pr-deployment-values-validation@main
        with:
          environment: ${{ matrix.environment }}
