# name: PR Validation - Main Starter

# on:
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   validation:
#     name: "Validation – ${{ matrix.environment }}"
#     strategy:
#       fail-fast: false
#       matrix:
#         environment: [dev, qa, vapt]
#     uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/common-pr-deployment-values-validation.yaml@main
#     with:
#       environment: ${{ matrix.environment }}


name: PR Validation - Main Starter

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  extract-ref:
    runs-on: ubuntu-latest
    outputs:
      infra_commons_tag: ${{ steps.extract_tag.outputs.infra_commons_tag }}
    steps:
      - name: Extract ref/tag from current workflow
        id: extract_tag
        run: |
          
          echo "GITHUB_WORKFLOW_REF=${GITHUB_WORKFLOW_REF}"
          REF=$(echo "$GITHUB_WORKFLOW_REF" | cut -d'@' -f2 | cut -d'/' -f3)
          echo "infra_commons_tag=${REF}" >> $GITHUB_OUTPUT
          echo "Extracted ref/tag: $REF"

  validation:
    name: "Validation – ${{ matrix.environment }}"
    needs: extract-ref
    uses: roberto-mondello-dgt/cache-helm-test/.github/workflows/common-pr-deployment-values-validation.yaml@main
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, vapt]
    with:
      environment: ${{ matrix.environment }}
      infra_commons_tag: ${{ needs.extract-ref.outputs.infra_commons_tag }}
